# Generated by Django 4.2.11 on 2024-03-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_catalogue_delete_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogue",
            name="location",
            field=models.CharField(default="Delhi", max_length=255),
        ),
    ]
