# Generated by Django 4.2.11 on 2024-03-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.IntegerField(max_length=10)),
                ("book_name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CBSE Course Books", "CBSE Course Books"),
                            ("Engineering Books", "Engineering Books"),
                            ("Novels", "Novels"),
                            ("GRE/GMAT/CAT/GATE Books", "GRE/GMAT/CAT/GATE Books"),
                            ("Magazines", "Magazines"),
                            ("Medical Books", "Medical Books"),
                            ("UPSC Books", "UPSC Books"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
            ],
        ),
    ]
