# Generated by Django 4.2.11 on 2024-03-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_sell"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sell",
            name="mobile",
            field=models.IntegerField(),
        ),
    ]
