# Generated by Django 4.2.11 on 2024-03-30 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0008_alter_sell_mobile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.FloatField()),
                ("sell_or_donate", models.CharField(max_length=255)),
                ("seller_name", models.CharField(max_length=255)),
                ("negotiable_price", models.BooleanField(default=True)),
                ("location", models.CharField(default="Delhi", max_length=255)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="item_images"),
                ),
                ("is_sold", models.BooleanField(default=False)),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verify_items",
                        to="catalog.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verify_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Sell",
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_items",
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
