# Generated by Django 4.2.11 on 2024-03-30 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_verify_delete_sell_alter_catalogue_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seller_name", models.CharField(max_length=255)),
                ("email", models.CharField(default="NA", max_length=255)),
                ("mobile", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(default=1)),
                ("location", models.CharField(default="Delhi", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="item_images"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donator_items",
                        to="catalog.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seller_name", models.CharField(max_length=255)),
                ("email", models.CharField(default="NA", max_length=255)),
                ("mobile", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(default=1)),
                ("location", models.CharField(default="Delhi", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.FloatField()),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="item_images"),
                ),
                ("negotiable_price", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_items",
                        to="catalog.category",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="catalogue",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="catalogue",
            name="created_by",
        ),
        migrations.AddField(
            model_name="catalogue",
            name="email",
            field=models.CharField(default="NA", max_length=255),
        ),
        migrations.DeleteModel(
            name="Verify",
        ),
    ]
