# Generated by Django 4.2.11 on 2024-03-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_donator_seller_remove_catalogue_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donator",
            name="from_time",
            field=models.TimeField(default=10),
        ),
        migrations.AlterField(
            model_name="donator",
            name="mobile",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="donator",
            name="seller_name",
            field=models.CharField(default="NA", max_length=255),
        ),
        migrations.AlterField(
            model_name="donator",
            name="to_time",
            field=models.TimeField(default=22),
        ),
        migrations.AlterField(
            model_name="seller",
            name="seller_name",
            field=models.CharField(default="NA", max_length=255),
        ),
    ]
