# Generated by Django 4.2.11 on 2024-03-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_alter_donator_from_time_alter_donator_to_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donator",
            name="from_time",
            field=models.TimeField(default="09:00"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="from_time",
            field=models.TimeField(default="09:00"),
        ),
    ]
