# Generated by Django 4.2.11 on 2024-03-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_alter_donator_location_alter_seller_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donator",
            name="location",
            field=models.CharField(default="Delhi", max_length=255),
        ),
        migrations.AlterField(
            model_name="seller",
            name="location",
            field=models.CharField(default="Delhi", max_length=255),
        ),
    ]
